### ISSUE TITLE
Chopped but not slopped

### ISSUE THREAD

**Issue by macadev** [diegomacario/Teapong#2]
Baby girl,

It is I, Chicago, responding to your SOS request. Wishing you a swift completion of this soup. It sure's getting complex with all those ingredients, specially the assembly and C#. Some might say it's chopped, but not slopped.

Anywho, Drake loves you. Take care. Once we are slurping soup, we'll see how nothing was the same, ever. Watch out for them Scorpions too. You'll thank me later. Enjoy the views too.

Good night,
[Chicago's Simple Soups.](https://soundcloud.com/octobersveryown/drake-im-on-one-chopped-up-not)

**Comment by diegomacario** [comment]
Dear dAnDY mAc,

Well ain't this one heck of a cluster fudge. At this point, I'm just holding on to my pants and hoping for the best.

They don't call me "Code Duplication McGee" for nothing. If it gotta be done in two different places, you betcha imma implement it twice.

That reminds me that I should dereference some null pointers just for the thrill of it. Ain't nothing more exciting that undefined behaviour. It's like jumping into a black hole. You gonna get spaghettified, and it gonna hurt, but who knows, you might end up somewhere cool.

Anywho, just looking forward to getting this out of the kitchen. For now, imma close this issue with Barbrenda's funniest joke:

Ooooh Darnell...
